### ISSUE TITLE
Customize Playlist

### ISSUE THREAD

**Issue by Yehezkiel01** [nus-angklung/gili#40]
This is what youtube's playlist looks like:
![image](https://user-images.githubusercontent.com/39835686/105160278-0507bc80-5b4b-11eb-8bbb-fa125e8dddb3.png)

This is what SoundCloud's playlist looks like:
![image](https://user-images.githubusercontent.com/39835686/105160431-33859780-5b4b-11eb-8bf2-d9dafb4cf718.png)

This is what Spotify's playlist looks like:
![image](https://user-images.githubusercontent.com/39835686/105160470-3ed8c300-5b4b-11eb-8ce0-e28cee75405d.png)

This is what we are intending to do initially:
![image](https://user-images.githubusercontent.com/39835686/105160500-4730fe00-5b4b-11eb-82a7-eee8f126e593.png)

I personally feels like Spotify's playlist look the most intuitive, but I don't think we can upload there. So, It maybe the best if we can try to customize the UI to looks like what we are intending to do initially.

Some reference:
[Youtube API](https://developers.google.com/youtube/v3/docs/playlists) (Useful for getting the playlist properties and we'll decide where to put the UI element)
https://github.com/Ashish-Bansal/audio-only-youtube (Maybe useful for converting videos into audio-only, more details can be found on this [function on line 65](https://github.com/Ashish-Bansal/audio-only-youtube/blob/7a6707dfd615d569e23e8f7b671732a29d97615e/src/js/background.ts#L65))

**Comment by RussellDash332** [comment]
Currently attaching the embed playlist of past angklung performances. New WIP

**Comment by RussellDash332** [comment]
https://www.labnol.org/internet/youtube-audio-player/26740/
@Yehezkiel01 what do you think?
