### ISSUE TITLE
Our playlist volume bar is having a seizure... :')

### ISSUE THREAD

**Issue by Yehezkiel01** [nus-angklung/gili#43]
https://user-images.githubusercontent.com/39835686/105628332-36e49000-5e77-11eb-8b2c-bda5f1be3cf4.mov

Somehow when we slide the volume bar, it's shaking a little bit

**Comment by RussellDash332** [comment]
It is an optical illusion. The indicator never goes over the mouse.
;-) @Yehezkiel01
